--------------------------------------------------------
--  DDL for Table SANDBOX
--------------------------------------------------------

  CREATE TABLE "IRBCHOICETICADM"."SANDBOX" 
   (	"WORD" VARCHAR2(200 BYTE), 
	"LENGTH" NUMBER(*,0), 
	"ACOUNT" NUMBER, 
	"BCOUNT" NUMBER, 
	"CCOUNT" NUMBER, 
	"DCOUNT" NUMBER, 
	"ECOUNT" NUMBER, 
	"FCOUNT" NUMBER, 
	"GCOUNT" NUMBER, 
	"HCOUNT" NUMBER, 
	"ICOUNT" NUMBER, 
	"JCOUNT" NUMBER, 
	"KCOUNT" NUMBER, 
	"LCOUNT" NUMBER, 
	"MCOUNT" NUMBER, 
	"NCOUNT" NUMBER, 
	"OCOUNT" NUMBER, 
	"PCOUNT" NUMBER, 
	"QCOUNT" NUMBER, 
	"RCOUNT" NUMBER, 
	"SCOUNT" NUMBER, 
	"TCOUNT" NUMBER, 
	"UCOUNT" NUMBER, 
	"VCOUNT" NUMBER, 
	"WCOUNT" NUMBER, 
	"XCOUNT" NUMBER, 
	"YCOUNT" NUMBER, 
	"ZCOUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IRBCHOICE_DATA" ;
